version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: mydietitian-postgres
    restart: always
    environment:
      POSTGRES_DB: mydietitian_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - mydietitian_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: mydietitian-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mydietitian.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  mydietitian_pgdata:
